In [3]:
import pandas as pd
import numpy as np
import os 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
filename = os.path.join(os.getcwd(), "WeInspectB.csv")
df = pd.read_csv(filename, header=0)

df.head()

,City,State,Zip,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,...,"Eyes, Ears, Nose, & Throat",Resipiratory,Digestive,Circulatory,Skin,Brain,Nervous,Urinary,Immune,Reproductive
0,Mountain Brook,Alabama,35223,ND,Nd,14,Nd,NaN,11,Nd,...,"Sneezing/Allergies, Dry/Irritated eyes, Chroni...",NaN,"Diarrhea/Constipation, Bloating, Abdominal pai...","Raynaud's phenomenon, Low or reactive blood pr...","Itchy/Peeling skin, Skin rash, Fungal infections",Brain fog,"Anxiousness, Fatigue",Overactive bladder,NaN,"Changes in menstrual cycle, Inconsistent menst..."
1,Wasilla,Alaska,99623,ND,ND,12,ND,5,ND,ND,...,"Sneezing/Allergies, Runny nose/Post-nasal drip...","Shortness of breath, Chronic dry cough, Chroni...","Significant weight gain/loss, Diarrhea/Constip...","Cherry angiomas, Easy bruising/bleeding","Itchy/Peeling skin, Skin rash, Eczema","Brain fog, Memory loss, Anger/Aggressiveness","Anxiousness, Depression, Headache, Migraine, I...",NaN,Long-lasting colds,"Vaginal yeast or bacterial infections, Hormone..."
2,Soldotna,Alaska,99669-8654,ND,3,3,234,NaN,6,ND,...,"Sneezing/Allergies, Runny nose/Post-nasal drip...","Shortness of breath, Heaviness in the chest","Significant weight gain/loss, Bloating, Sweet ...","Spider veins, Easy bruising/bleeding, Iron def...","Itchy/Peeling skin, Flushing, Fungal infections","Brain fog, Confusion, Memory loss, Trouble fin...","Anxiousness, Depression, Headache, Insomnia, F...",Overactive bladder,"Increased susceptibility to infection, Chronic...","Changes in menstrual cycle, Inconsistent menst..."
3,Soldotna,Alaska,99669,ND,ND,ND,ND,NaN,ND,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anchorage,Alaska,99508-4014,64,5,32,ND,NaN,6,ND,...,"Runny nose/Post-nasal drip, Ear popping/ringin...",NaN,Significant weight gain/loss,"Spider veins, Cherry angiomas, Raynaud's pheno...",Eczema,"Brain fog, Trouble finding the right word, Ang...","Anxiousness, Fatigue",NaN,NaN,NaN

In [5]:
columns = ['Diagnoses', 'Eyes, Ears, Nose, & Throat', 'Resipiratory', 'Digestive', 'Circulatory', 'Skin', 'Brain', 
           'Nervous', 'Urinary', 'Immune', 'Reproductive']
uniqueValues = df[columns]
uniqueValues.head()

,Diagnoses,"Eyes, Ears, Nose, & Throat",Resipiratory,Digestive,Circulatory,Skin,Brain,Nervous,Urinary,Immune,Reproductive
0,"Hyperthyroid/Hypothyroid, IBS, PCOS","Sneezing/Allergies, Dry/Irritated eyes, Chroni...",NaN,"Diarrhea/Constipation, Bloating, Abdominal pai...","Raynaud's phenomenon, Low or reactive blood pr...","Itchy/Peeling skin, Skin rash, Fungal infections",Brain fog,"Anxiousness, Fatigue",Overactive bladder,NaN,"Changes in menstrual cycle, Inconsistent menst..."
1,NaN,"Sneezing/Allergies, Runny nose/Post-nasal drip...","Shortness of breath, Chronic dry cough, Chroni...","Significant weight gain/loss, Diarrhea/Constip...","Cherry angiomas, Easy bruising/bleeding","Itchy/Peeling skin, Skin rash, Eczema","Brain fog, Memory loss, Anger/Aggressiveness","Anxiousness, Depression, Headache, Migraine, I...",NaN,Long-lasting colds,"Vaginal yeast or bacterial infections, Hormone..."
2,"CIRS, MCAS","Sneezing/Allergies, Runny nose/Post-nasal drip...","Shortness of breath, Heaviness in the chest","Significant weight gain/loss, Bloating, Sweet ...","Spider veins, Easy bruising/bleeding, Iron def...","Itchy/Peeling skin, Flushing, Fungal infections","Brain fog, Confusion, Memory loss, Trouble fin...","Anxiousness, Depression, Headache, Insomnia, F...",Overactive bladder,"Increased susceptibility to infection, Chronic...","Changes in menstrual cycle, Inconsistent menst..."
3,"Auto-Immune Disease, Lyme Disease, Hyperthyroi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"CIRS, Hyperthyroid/Hypothyroid, PCOS, Candidia...","Runny nose/Post-nasal drip, Ear popping/ringin...",NaN,Significant weight gain/loss,"Spider veins, Cherry angiomas, Raynaud's pheno...",Eczema,"Brain fog, Trouble finding the right word, Ang...","Anxiousness, Fatigue",NaN,NaN,NaN

In [6]:
for i in columns:
    systemSymptomList = (df[i].dropna()   # Drop any remaining NaNs (though there shouldn't be any after fillna)
                     .replace('', '0')    # Replace empty strings with '0'
                     .str.lower()         # Convert to lowercase
                     .str.replace(" ", "") # Remove spaces
                     .str.split(',')      # Split by commas
                     .explode()           # Explode lists to rows
                     .loc[lambda x: x != '0'] # Filter out '0' values
                     .dropna()            # Drop any remaining NaNs (though there shouldn't be any after fillna)
                     .unique())           # Get unique values
    
    for j in systemSymptomList:
        newColumn = str(i) + "_" + str(j)
        df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
    systemSymptomList = []
df.columns

/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)
/tmp/ipykernel_3101/3790493406.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[newColumn] = df[i].apply(lambda x: 1 if j in str(x).lower().replace(" ", "") else 0)

Index(['City', 'State', 'Zip', 'Aspergillus flavus/oryzae',
       'Aspergillus fumigatus', 'Aspergillus niger', 'Aspergillus ochraceus',
       'Aspergillus penicillioides', 'Aspergillus restrictus*',
       'Aspergillus sclerotiorum',
       ...
       'Immune_chronicmonoorepstein-barrvirus',
       'Immune_frequentherpesoutbreaks',
       'Immune_viralinfectionsbecomebacterial',
       'Immune_increasedsusceptibilitytocancer',
       'Reproductive_changesinmenstrualcycle',
       'Reproductive_inconsistentmenstrualcycle',
       'Reproductive_vaginalyeastorbacterialinfections',
       'Reproductive_jockitch', 'Reproductive_infertilityinbothgenders',
       'Reproductive_hormoneimbalances'],
      dtype='object', length=163)

In [7]:
df.head(15)

,City,State,Zip,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,...,Immune_chronicmonoorepstein-barrvirus,Immune_frequentherpesoutbreaks,Immune_viralinfectionsbecomebacterial,Immune_increasedsusceptibilitytocancer,Reproductive_changesinmenstrualcycle,Reproductive_inconsistentmenstrualcycle,Reproductive_vaginalyeastorbacterialinfections,Reproductive_jockitch,Reproductive_infertilityinbothgenders,Reproductive_hormoneimbalances
0,Mountain Brook,Alabama,35223,ND,Nd,14,Nd,NaN,11,Nd,...,0,0,0,0,1,1,1,1,1,1
1,Wasilla,Alaska,99623,ND,ND,12,ND,5,ND,ND,...,0,0,0,0,0,0,1,0,0,1
2,Soldotna,Alaska,99669-8654,ND,3,3,234,NaN,6,ND,...,1,0,0,0,1,1,0,0,0,1
3,Soldotna,Alaska,99669,ND,ND,ND,ND,NaN,ND,ND,...,0,0,0,0,0,0,0,0,0,0
4,Anchorage,Alaska,99508-4014,64,5,32,ND,NaN,6,ND,...,0,0,0,0,0,0,0,0,0,0
5,Sherwood Park,Alberta,T8A6P1,ND,309,4,ND,15,ND,8,...,0,0,0,0,0,0,0,0,0,0
6,Crossfield,Alberta,T0M0R0,<1,1,11,ND,NaN,3,ND,...,0,0,0,0,0,0,0,0,0,1
7,Calgary,Alberta,T2W 4C1,ND,17,396,ND,NaN,ND,ND,...,0,0,0,0,0,0,0,0,0,0
8,Scottsdale,Arizona,85251,5,3,83,9,428,ND,3,...,0,0,0,0,0,0,0,0,0,1
9,Tucson,Arizona,85701,92,21,"4,807",60,"1,848",3,7,...,1,1,0,0,0,0,0,0,0,0
10,Tucson,Arizona,85743,33,10,160,10,141,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Lake Havasu City,Arizona,86406,21*,9,1202**,22*,1173*,ND,4,...,0,0,0,0,0,0,0,0,0,0
12,Mesa,Arizona,85213,0,0,30,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0
13,Queen Creek,Arizona,85142,132,30,1792,40,939,5,14,...,0,0,0,0,0,0,0,0,0,0
14,Phoenix,Arizona,85024,9,7,195,5,53,ND,ND,...,0,0,0,0,0,0,0,0,0,0

In [8]:
mole_columns = df.iloc[:, 3:40]
mole_columns.head()

,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,Aspergillus sydowii,Aspergillus unguis,Aspergillus versicolor,...,Acremonium strictum,Alternaria alternata,Aspergillus ustus,Cladosporium cladosporioides 1,Cladosporium cladosporioides 2,Cladosporium herbarum,Epicoccum nigrum,Mucor amphibiorum*,Penicillium chrysogenum,Rhizopus stolonifer
0,ND,Nd,14,Nd,NaN,11,Nd,Nd,Nd,Nd,...,9,19,15,NaN,NaN,NaN,372,10,29,6
1,ND,ND,12,ND,5,ND,ND,ND,ND,ND,...,ND,ND,ND,470,12,114,67,24,111*,ND
2,ND,3,3,234,NaN,6,ND,5,ND,279,...,ND,ND,119,NaN,NaN,NaN,60,173,70,ND
3,ND,ND,ND,ND,NaN,ND,ND,ND,ND,6,...,ND,ND,ND,NaN,NaN,NaN,435,4,49,ND
4,64,5,32,ND,NaN,6,ND,ND,ND,6,...,2,3,<1,NaN,NaN,NaN,2,7,83,12

In [9]:
#turning all 'NaN', strings, and <0 to zero
for i in mole_columns:
    filtered = df.loc[~df[i].astype(str).str.isnumeric() | df[i].isna(), i].unique()
    print (filtered)

['ND' '<1' '21*' 'nd' 'N/D' 'N D' '22*' 'ND, <1' 'Nd' '33*' 'Hhh']
['Nd' 'ND' '39*' 'nd' '57*' 'ND, <1' 'N D' '<1' '61 *' '35*' '33*' '50*'
 'Hhh']
['ND' '4,807' '1202**' '713**' '161*' '80 *' '142*' '1,691' '464**'
 '272 *' '564**' 'ND, <1' '6,229' '40 *' '438**' '68 *' '44*' '194 *'
 '3422**' '50*' '74 *' '1,248' 'Nd' 'NF' '320*' '127*' '101*' '48*' '184*'
 '123*' '86*' '1,018' '632**' '206*' '195*' '276*' 'Hh']
['Nd' 'ND' '22*' 'nd' '<1' 'N D' '48*' 'ND, <1' '23 *' '73*' 'NDNDND'
 'N/D' '27*' '28*' 'Hh']
[nan '1,848' '1173*' 'ND' '1,528' '2,602' '1,001' '4,405' '1676*']
['ND' 'Nd' '25*' 'nd' 'N/D' 'N D' 'ND, <1' '88 *' '<1' '37*' '720**' '22*'
 '393 * *' '47*' '41*' '29*' '30*' '20*' '77*' 'Hh']
['Nd' 'ND' '<1' '35*' 'nd' 'N D' '138*' 'ND, <1' 'o' 'na' '37 *' '1,186'
 '39 *' 'N/D' '20 *' '41*' '74*' '23*' '27*' 'Hh']
['Nd' 'ND' '54*' 'nd' 'N/D' 'N D' '58*' 'ND, <2' 'na' 'Ne' 'NF' '89*'
 '64*' '34*' 'Hh']
['Nd' 'ND' '<1' 'nd' 'N/D' 'N D' '1, 1' '<' 'na' '25*' '1<' '41*' '83*'
 'Hh']
['Nd' 'ND' '67*' '106*' 'nd' 'N/D' 'N D' '195 *' '241**' '330, 74' '61 *'
 '29*' '159 *' '305**' '21*' '41*' '195*' '46*' '43 *' '75*' '1,749'
 '181*' '163*' '38*' '50*' '27,089' '32*' '142*' '100*' '59*' '196*'
 '179*' '28*' 'Hh']
['1,554' '2,231' '6,624' '51,391' '11,515' '1,168' '1,001' '4,624*'
 '2,184' '24,177' '1,579' '8,584' '384,895' '1,279' '4,470 *' '6453*'
 '240, 54' '1,731' '7,375' '11,243' '1,798' '18,882' '2,158' '4527*'
 '3,375' '3,295' '6,672' '6,291 *' '2,088' '4,588' '6,366' '6,185' '3,902'
 '1,406' '2990*' '11,258' '5,330' '2,960' '2,008' '613,540' '1,481'
 '2,287' '3464*' '1,278' '12,332' '11,031*' '2,010' '5,943 *' 'Nd'
 '15,925*' '5,543' '3,065' '10,409' '48,433' '3,362' '1,083' '2,058'
 '4,520' '2,621' '26,864' '10,993' '2,608' '4279*' '1,768' '40569**' 'ND'
 '11, 190' '12,669' '3,271' '10556*' '3,081' '13,130' '4097*' '4,528'
 '1,346' '85,759' 'Hh']
['ND' '27*' '<1' '80*' 'nd' 'N D' '116*' '1, 1' 'Nd' '4/40' '532 **'
 '23 *' '1,168' '113*' '64*' 'Hh']
['ND' '<1' '18,459' 'ND, <1' 'nd' '216 *' '1,510' 'Nd' '406*' '187 *'
 '180*' '164*' '1,505' '235*' '422*' 'N D' '209*' '<!' 'Hh']
['6,323' '4,009' '1,159' '410, 91' 'ND' '1,186' '1,563' '3,161' '2,962 *'
 'nd' '2,516' '1,380' '1,830' '3,786' 'Nd' '2,133*' '1,530' '10,843'
 '4,217' '1,065' '3,712*' '2011*' 'Hh']
['ND' '110*' 'nd' '1, 1' '27 *' 'Nd' '<1' 'N D' 'N/D' '43*' 'BD' '33*'
 '22*' 'Hh']
['259*' '157*' '1,213**' '1,444' '475 *' '1,484' '2,999' '236 *' '531*'
 'ND, <1' 'ND' 'Nd' 'I 9' '70 *' '342*' '86,978' '183 *' 'nd' '119*' '53*'
 '59*' '4,038' '175*' '512 * *' '89*' '104*' '868**' '4,803' '129*' '134*'
 '114*' '<1' '192*' '182*' '619**' '390*' 'Hh']
['ND' '<1' '2,529' '164*' '36*' 'nd' '26 *' '24 *' '81*' '120, 27' 'Nd'
 '147 *' 'N D' '1,137' '48*' '79*' '31*' '89*' '198*' '28*' 'N/D' '6,292'
 '37*' '26*' '223**' '505**' '190*' '250*' 'Hh']
['Nd' '20*' '24*' 'ND' '14*' '11*' 'nd' 'N/D' '68 *' '13*' 'ND, <1' 'N D'
 '27*' '456 **' '18*' '340**' '14 *' '36*' '26*' '65*' '60*' '10*' '59*'
 '83*' '971**' 'Hh']
['Nd' 'ND' '<1' '22*' 'NE' '18*' 'N/D' '61 *' '14*' 'ND, <1' 'N D' 'nd'
 '364**' '28*' '0`' '12*' '63*' 'Hh']
['Nd' 'ND' '<1' 'nd' 'N D' 'ND, <3' '13*' 'Do not see listed' 'N/D' '1<'
 'Hh']
['ND' '936**' '37*' 'nd' 'N/D' 'N D' '30, 7' 'NF' 'Nd' '1,738' '33 *' '<1'
 '41*' '70*' '215*' 'Hh']
['Nd' 'ND' '<1' 'nd' 'N D' '95*' '3, 1' '32*' '80*' '38 *' 'BD' ',1' 'Hh']
['ND' '<1' 'nd' '23 *' '4900, 1100' 'Nd' '20*' '38*' 'N D' 'Hh']
['Nd' 'ND' '<1' 'nd' 'N D' 'ND, <1' 'NE' 'N d' '29*' 'N/D' '28*' 'Hh']
['ND' 'Nd' '<1' '119*' '75*' 'nd' '1,518' '63 *' '56*' 'ND, <1' '37 *'
 '29*' '38 *' '>1' '26*' '89*' '33*' '39*' '37*' '75 *' '157*' '1<' '49*'
 '2839 ***' '28*' '68*' '38*' 'Hh']
['ND' 'nd' '268*' '2, 1' '821*' '434 *' 'Nd' '298*' 'Hh']
[2.57000000e+01 1.36000000e+01 2.22000000e+01 1.01000000e+01
 1.72800000e+01 1.76000000e+01 1.74700000e+01 2.75000000e+01
 3.41000000e+01 4.28000000e+01 2.24000000e+01 3.52000000e+01
 8.10000000e+00 3.20000000e+01 2.45000000e+01 3.55000000e+01
 7.90000000e+00 3.05000000e+01 3.29000000e+01 2.09000000e+01
 2.02000000e+01 2.78000000e+01 2.18000000e+01 1.43000000e+01
 3.66000000e+01 2.53000000e+01 2.13000000e+01 4.56000000e+01
 4.23400000e+01 5.07000000e+01 1.30000000e+01 1.88000000e+01
 1.92000000e+01 2.86000000e+01 2.61000000e+01 2.02400000e+01
 2.38000000e+01 2.06600000e+01 1.75300000e+01 2.25200000e+01
 3.86700000e+01 6.30000000e+00 3.62000000e+01 4.02000000e+01
 3.89000000e+01 3.41200000e+01 7.50000000e+00 3.16000000e+01
 3.40000000e+01 3.76500000e+01 2.47000000e+01 4.22000000e+01
 3.12000000e+01 2.21000000e+01 2.59900000e+01 1.62000000e+01
 3.95700000e+01 1.95000000e+01 3.27500000e+01 3.48000000e+01
 1.07000000e+01 5.21000000e+01 5.02000000e+01 2.28100000e+01
 5.10000000e+01 3.35100000e+01 2.81100000e+01 3.32000000e+01
 2.19000000e+01 4.58000000e+01 1.69000000e+01 3.39000000e+01
 4.36000000e+01 3.47100000e+01 2.74000000e+01 2.79800000e+01
 1.19000000e+01 7.07900000e+00 4.24000000e+01 1.97000000e+01
 2.50000000e+01 3.44000000e+01 3.33000000e+01 5.93000000e+01
 2.48000000e+01 2.85000000e+01 0.00000000e+00 4.21000000e+01
 1.47000000e+01 4.32000000e+01 1.96000000e+01 1.64000000e+01
 2.99900000e+01 4.12000000e+01 5.80000000e+00 4.90000000e+01
 4.60000000e+01 1.85700000e+01 2.81300000e+01 1.21000000e+01
 1.49800000e+01 2.80000000e+01 6.60000000e+00 2.14000000e+01
 2.42000000e+01 1.65000000e+01 3.63000000e+01 2.34000000e+01
 2.20000000e+01 2.35000000e+01 4.76560000e+01 1.86000000e+01
 1.87000000e+01 4.29000000e+01 2.29000000e+01 2.25000000e+01
 2.23900000e+01 3.69000000e+01 5.46000000e+01 1.60000000e+01
 1.17000000e+01 3.08000000e+01 2.17000000e+01 2.44000000e+01
 2.64000000e+01 2.33000000e+01 2.46000000e+01 3.34000000e+01
 2.93000000e+01 3.59000000e+01 3.30000000e+01 3.06000000e+01
 1.91000000e+01 3.22000000e+01 2.63000000e+01 5.45000000e+01
 2.36000000e+01 1.08000000e+01 2.89000000e+01 3.11000000e+01
 2.91000000e+01 5.82000000e+01 4.45000000e+01 2.90000000e+01
 2.16400000e+01 2.83000000e+01 2.79700000e+01 4.09000000e+01
 3.86000000e+01 3.26000000e+01 3.70000000e+01 2.51000000e+01
 2.51500000e+01 4.23000000e+01 1.59300000e+01 2.56400000e+01
 3.79000000e+01 3.57000000e+01 1.48700000e+01 4.10000000e+01
 3.17000000e+01 1.81000000e+01 4.57000000e+01 1.48100000e+01
 4.30000000e+00 2.84100000e+01 3.94000000e+01 1.33100000e+01
 1.92600000e+01 1.60700000e+01 2.72000000e+01 2.76000000e+01
 2.31000000e+01 3.42000000e+01 3.80000000e+01 9.40000000e+00
 5.20000000e+01 3.47000000e+01 2.58000000e+01 1.80000000e+01
 1.52000000e+01 2.99000000e+01 3.97000000e+01 2.43000000e+01
 2.68100000e+01 2.28000000e+01 1.20700000e+03 2.23000000e+01
 3.02200000e+01 2.01300000e+01 3.84000000e+01 4.69000000e+01
 1.97900000e+01 2.92600000e+01 2.36800000e+01 3.48500000e+01
 2.04500000e+01 2.47400000e+01 5.12000000e+01 3.28000000e+01
 5.57000000e+01 3.96000000e+01 2.63200000e+01 2.26000000e+01
 1.98000000e+01 3.46000000e+01 1.90000000e+01 4.46000000e+01
 4.27000000e+01 4.15000000e+01 2.27000000e+01 3.68000000e+01
 2.52000000e+01 2.53000000e+02 2.98000000e+01 1.73000000e+01
 3.07000000e+01 4.20000000e+01 1.79000000e+01 4.64000000e+01
 5.71000000e+01 3.60000000e+01 3.85000000e+01 1.48000000e+01
 1.61400000e+01 2.79000000e+01 3.96200000e+01 4.78000000e+01
 1.94000000e+01 1.72000000e+01 1.59000000e+01 2.40000000e+01
 2.62300000e+01 1.42000000e+01 1.41000000e+01 3.91000000e+01
 2.67000000e+01 2.60000000e+01 1.96200000e+01 5.38000000e+00
 4.61000000e+01 1.22900000e+01 2.73000000e+01 4.01000000e+01
 2.85700000e+01 3.50200000e+01 3.32400000e+01 2.13800000e+01
 3.99000000e+01 3.72000000e+01 3.51000000e+01 1.93000000e+01
 2.88000000e+01 2.55000000e+01 6.86000000e+01 3.02000000e+01
 2.00000000e+01 1.74000000e+01 1.61000000e+01 5.19700000e+03
 3.01000000e+01 1.28000000e+01 5.65000000e+01 1.00000000e+01
 5.30000000e+00 9.80000000e+00 4.85000000e+01 3.90000000e+01
 3.50000000e+01 4.03000000e+01 4.14000000e+01 4.38000000e+01
 1.38000000e+01 2.91000000e+02 5.40300000e+00 5.31000000e+01
 1.92400000e+01 5.27000000e+01 1.90500000e+01 1.15000000e+01
 3.73000000e+01 5.39000000e+01 3.03500000e+01 2.63700000e+03
 1.78000000e+01 2.80400000e+01 1.32400000e+04 1.58000000e+01
 1.85000000e+01 2.06000000e+01 3.81000000e+01 3.15000000e+01
 2.82000000e+01 3.58600000e+01 8.40000000e+00 2.07000000e+01
 3.58000000e+01 4.76000000e+01 1.67000000e+01 2.11000000e+01
 1.00100000e+01 2.30000000e+01 1.44000000e+01 2.19600000e+01
 3.74000000e+01 3.27000000e+01 2.00900000e+01 3.04000000e+01
 2.41000000e+01 1.10000000e+01 4.51000000e+01 2.37000000e+01
 3.93000000e+01 1.82000000e+01 1.78700000e+01 2.06800000e+01
 1.94700000e+01 1.63100000e+01 4.30300000e+01 2.48700000e+01
 1.99000000e+01 2.25700000e+01 4.67500000e+01 3.93500000e+01
 1.87700000e+01 2.52500000e+01 2.18200000e+01 5.17500000e+01
 3.19000000e+01 2.70000000e+01 3.75000000e+01 4.74000000e+01
 1.50000000e+01 3.37000000e+01 1.46000000e+01 1.07200000e+01
 5.05000000e+01 8.51000000e+02 3.88000000e+01 2.03700000e+01
 3.15500000e+01 3.56000000e+01 4.26600000e+01 2.59000000e+01
 3.49000000e+01 2.49200000e+01 4.75000000e+01 1.34000000e+01
 3.35000000e+01 3.76000000e+00 4.44200000e+01 3.23100000e+01
 4.77000000e+01 1.68000000e+01 2.96000000e+01 1.40000000e+01
 4.37000000e+01 1.84000000e+01 2.92000000e+01 3.10000000e+01
 3.54000000e+01 3.24000000e+01 3.13200000e+01 6.39600000e+00
 3.88900000e+01 4.97000000e+01 3.03900000e+01 5.38000000e+01
 1.54400000e+01 1.88900000e+01 2.84700000e+01 2.68000000e+01
 7.23000000e+01 3.78000000e+01 8.06800000e+03 7.40000000e+01
 3.18000000e+01 3.78800000e+01 1.14500000e+01 2.61500000e+01
 1.84900000e+01 2.38200000e+01 3.19300000e+01 2.21100000e+01
 3.37600000e+01 2.03000000e+01 3.13000000e+01 1.50800000e+01
 4.00500000e+01 2.05000000e+01 1.51900000e+01 3.43000000e+01
 3.44900000e+04 1.56000000e+02 2.65000000e+02 1.42600000e+03
 2.66000000e+01 4.57866889e+08 2.44500000e+01 4.05900000e+01]
['ND' 'Nd' 'nd' 'NS' '<1' 'ND, <1' 'N D' '157 *' '51 *' '95*' '544**'
 '89 *' '777 ***' '1295**' '2,030' 'Hh']
['ND' '1,473' 'ND, <1' 'N D' '3/30' '<1' 'nd' '2,920*' '2,047' 'Nd' 'Hh']
['ND' '<1' '119*' 'nd' '102*' '157*' 'ND, <1' 'N D' '2,344' 'Nd' '70*'
 '71*' '73*' '69*' '38*' 'Hh']
[nan '2,118' '1,735' '4,999*' '4,311*' '3,043' '3,277' '6,605' '3,292'
 '4,544' 'ND' '4,987 *' '26,086' '3,153' '8,875' '2,188' '6,930' '4,734'
 '6,300' '7,234' '2,955' '6,679' '2,886' '1,120' '2,499' '14,202' '26.863'
 '6129*' '3844*' '2,362']
[nan '218*' '1,012**' '250 *' '79*' 'ND' '228 *' '61*' '<1' '100*' '2,112'
 '83*' '380*']
[nan '611*' '2,539' '2,515' '6,293' 'ND' '486 *' '2913*' 'Nd' '1,609 *'
 '2,639' '6236**' '35,214' '2,414*' '1,377' '10,945' '805*' '1211*']
['ND, <1' 'ND' '1/10' '1,663 *' '2,216*' '3,851' '1,030' '4,221' '2,019'
 '3,278' '1,887' '1,577' '26,952' '12,416**' '26,622**' '1,370' '7,906'
 '5,076*' '3,617 *' 'Nd' '2,858' '3,887' '2,125' '3601*' '4,077' '1419*'
 '1,111' '4,870' '2157*' '1,456' '1191*' '1,004' 'Hh']
['nd' 'ND' '2, 1' 'N D' '235 *' '2,157' '2,861' '196*' '<1' 'Nd' '267*'
 '4,354' '340*' '261*' '<' '151*' 'Hh']
['111*' '60*' 'ND' '268*' 'nd' '246 *' '644**' '190, 43' 'NF' 'Nd' '53 *'
 '524 **' '146 *' '7,549' '57*' '1,266' '303*' '395*' '4,054' '254*' '76*'
 '63*' 'Hh']
['ND' '20*' 'Nd' '<1' '22*' 'nd' 'N D' 'ND, <1' 'n/d' 'N/D' '13*' '28 *'
 'N d' 'O' '11*' 'Hh']

In [39]:
values_to_replace=['ND','<1','nd','N/D','N D','Nd', 'Hhh', 'nan', 'Hh', 'ND, <1','NDNDND', 'na','Ne','NF','<','n/d','o', 'BD','NaN', 'N d', 'ND<1','ND<2', 'ND<3', 'Donotseelisted','NE', '0`', '<!', 'I9', '1<', 'NE', '4/40', '1/10', 'O', '>1','NS', '3/30']
''
#values_to_replace = ['nd', '<1', 'n/d', 'n d', 'nd', 'hhh', 'nan', 'hh', 'nd, <1', 'ndndnd', 'na', 'ne', 'nf', '<', 'n/d', 'o', 'bd']

for i in mole_columns:
    for j in values_to_replace:
        df[i] = df[i].replace(j, '0')
        df[i] = df[i].fillna(0)
        df[i] = df[i].astype(str)
        df[i] = df[i].str.replace('*', '')
        df[i] = df[i].str.replace(' ', '')
        df[i] = df[i].str.replace(',', '')
        
        
    
df.head(6)

,City,State,Zip,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,...,Immune_chronicmonoorepstein-barrvirus,Immune_frequentherpesoutbreaks,Immune_viralinfectionsbecomebacterial,Immune_increasedsusceptibilitytocancer,Reproductive_changesinmenstrualcycle,Reproductive_inconsistentmenstrualcycle,Reproductive_vaginalyeastorbacterialinfections,Reproductive_jockitch,Reproductive_infertilityinbothgenders,Reproductive_hormoneimbalances
0,Mountain Brook,Alabama,35223,0.0,0.0,14.0,0.0,0.0,11.0,0.0,...,0,0,0,0,1,1,1,1,1,1
1,Wasilla,Alaska,99623,0.0,0.0,12.0,0.0,5.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,1
2,Soldotna,Alaska,99669-8654,0.0,3.0,3.0,234.0,0.0,6.0,0.0,...,1,0,0,0,1,1,0,0,0,1
3,Soldotna,Alaska,99669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,Anchorage,Alaska,99508-4014,64.0,5.0,32.0,0.0,0.0,6.0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,Sherwood Park,Alberta,T8A6P1,0.0,309.0,4.0,0.0,15.0,0.0,8.0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
df.head(7)

,City,State,Zip,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,...,Immune_chronicmonoorepstein-barrvirus,Immune_frequentherpesoutbreaks,Immune_viralinfectionsbecomebacterial,Immune_increasedsusceptibilitytocancer,Reproductive_changesinmenstrualcycle,Reproductive_inconsistentmenstrualcycle,Reproductive_vaginalyeastorbacterialinfections,Reproductive_jockitch,Reproductive_infertilityinbothgenders,Reproductive_hormoneimbalances
0,Mountain Brook,Alabama,35223,0.0,0.0,14.0,0.0,0.0,11.0,0.0,...,0,0,0,0,1,1,1,1,1,1
1,Wasilla,Alaska,99623,0.0,0.0,12.0,0.0,5.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,1
2,Soldotna,Alaska,99669-8654,0.0,3.0,3.0,234.0,0.0,6.0,0.0,...,1,0,0,0,1,1,0,0,0,1
3,Soldotna,Alaska,99669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,Anchorage,Alaska,99508-4014,64.0,5.0,32.0,0.0,0.0,6.0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,Sherwood Park,Alberta,T8A6P1,0.0,309.0,4.0,0.0,15.0,0.0,8.0,...,0,0,0,0,0,0,0,0,0,0
6,Crossfield,Alberta,T0M0R0,0.0,1.0,11.0,0.0,0.0,3.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [40]:
for i in mole_columns:
    filtered = df.loc[~df[i].astype(str).str.isnumeric() | df[i].isna(), i].unique()
    print (filtered)

['0.0' '64.0' '5.0' '92.0' '33.0' '21.0' '132.0' '9.0' '134.0' '4.0' '6.0'
 '22.0' '8.0' '93.0' '11.0' '2.0' '1.0' '10.0' '3.0' '17.0' '7.0' '13.0'
 '20.0' '14.0' '30.0' '26.0' '38.0' '12.0' '40.0' '34.0' '27.0' '58.0'
 '3048.0' '18.0' '16.0' '49.0' '143.0' '83.0' '116.0' '54.0' '23.0'
 '181.0' '24.0' '248.0' '82.0' '47.0' '140.0' '43.0' '42.0' '66.0' '45.0'
 '63.0' '68.0' '25.0' '35.0' '53.0' '44.0' '19.0' '415.0']
['0.0' '3.0' '5.0' '309.0' '1.0' '17.0' '21.0' '10.0' '9.0' '30.0' '7.0'
 '44.0' '4.0' '20.0' '16.0' '2.0' '6.0' '8.0' '140.0' '22.0' '14.0' '13.0'
 '39.0' '29.0' '38.0' '25.0' '15.0' '176.0' '371.0' '23.0' '27.0' '46.0'
 '170.0' '99.0' '41.0' '77.0' '59.0' '11.0' '57.0' '79.0' '15641.0' '26.0'
 '24.0' '688.0' '82.0' '31.0' '73.0' '156.0' '61.0' '91.0' '302.0' '40.0'
 '12.0' '19.0' '50.0' '34.0' '87.0' '18.0' '226.0' '63.0' '76.0' '42.0'
 '103.0' '218.0' '32.0' '51.0' '373.0' '3002.0' '33.0' '337.0' '98.0'
 '62.0' '53.0' '93.0' '47311.0' '54.0' '36.0' '66.0' '184.0' '90.0'
 '121.0' '35.0' '2536.0' '169.0' '43.0' '285.0' '85.0' '45.0' '130.0'
 '1100.0' '80.0' '600.0' '109.0' '120.0' '6812.0' '119.0' '110.0' '237.0'
 '28.0' '133.0']
['14.0' '12.0' '3.0' '0.0' '32.0' '4.0' '11.0' '396.0' '83.0' '4807.0'
 '160.0' '1202.0' '30.0' '1792.0' '195.0' '3129.0' '102.0' '55.0' '190.0'
 '96.0' '127.0' '158.0' '153.0' '128.0' '69.0' '7.0' '87.0' '360.0'
 '113.0' '2.0' '44.0' '170.0' '240.0' '100.0' '48.0' '23.0' '73.0' '63.0'
 '510.0' '22.0' '713.0' '161.0' '120.0' '300.0' '8.0' '575.0' '1110.0'
 '260.0' '108.0' '101.0' '3631.0' '1914.0' '80.0' '458.0' '2800.0' '142.0'
 '439.0' '310.0' '182.0' '72.0' '3431.0' '1691.0' '2700.0' '468.0'
 '1300.0' '270.0' '463.0' '898.0' '246.0' '741.0' '464.0' '900.0' '13.0'
 '272.0' '400.0' '171.0' '564.0' '320.0' '204.0' '110.0' '999.0' '10.0'
 '1442.0' '107.0' '283.0' '327.0' '416.0' '6300.0' '138.0' '381.0' '237.0'
 '250.0' '117.0' '208.0' '9.0' '6229.0' '6.0' '77.0' '98.0' '603.0' '19.0'
 '1623.0' '1.0' '140.0' '94.0' '410.0' '200.0' '145.0' '28.0' '350.0'
 '245.0' '36.0' '134.0' '50.0' '1304.0' '39.0' '177.0' '148.0' '620.0'
 '452.0' '46.0' '2200.0' '74.0' '730.0' '43.0' '58.0' '295.0' '14775.0'
 '194.0' '40.0' '114.0' '448.0' '445.0' '558.0' '59.0' '29.0' '33.0'
 '528.0' '686.0' '24.0' '948.0' '438.0' '17.0' '683.0' '2598.0' '54.0'
 '18.0' '47.0' '164.0' '169.0' '68.0' '377.0' '88.0' '860.0' '15.0'
 '180.0' '351.0' '104.0' '26.0' '42.0' '343.0' '4591.0' '5.0' '89.0'
 '810.0' '206.0' '610.0' '150.0' '144.0' '118.0' '57.0' '159.0' '565.0'
 '130.0' '798.0' '49.0' '1137.0' '38.0' '710.0' '850.0' '290.0' '729.0'
 '70.0' '115.0' '449.0' '41.0' '3422.0' '1013.0' '82.0' '45.0' '111.0'
 '34.0' '3357.0' '172.0' '20.0' '254.0' '230.0' '354.0' '278.0' '493.0'
 '309.0' '53.0' '1558.0' '93.0' '330.0' '192.0' '51.0' '784.0' '21.0'
 '403.0' '37.0' '90.0' '647.0' '2341.0' '2651.0' '569.0' '1248.0' '210.0'
 '1045.0' '419.0' '1761.0' '106.0' '263.0' '2461.0' '2708.0' '2397.0'
 '27.0' '774.0' '227.0' '399.0' '218.0' '720.0' '402.0' '76.0' '137.0'
 '66.0' '116.0' '136.0' '315.0' '16.0' '35.0' '556.0' '103.0' '201.0'
 '763.0' '1400.0' '983.0' '64.0' '5200.0' '65.0' '570.0' '7500.0' '632.0'
 '198.0' '213.0' '3087.0' '52.0' '383.0' '965.0' '219.0' '473.0' '109.0'
 '235.0' '312.0' '319.0' '1057.0' '185.0' '541.0' '382.0' '184.0' '84.0'
 '176.0' '173.0' '123.0' '225.0' '522.0' '549.0' '86.0' '1018.0' '2560.0'
 '220.0' '62.0' '197.0' '520.0' '1048.0' '276.0' '2300.0' '31.0' '3400.0'
 '1500.0' '25.0' '67.0' '91.0' '440.0' '311.0' '149.0']
['0.0' '234.0' '9.0' '60.0' '10.0' '22.0' '40.0' '5.0' '58.0' '8.0' '4.0'
 '7.0' '13.0' '28.0' '29.0' '170.0' '46.0' '72.0' '6.0' '3.0' '2.0' '16.0'
 '14.0' '30.0' '11.0' '20.0' '150.0' '26.0' '38.0' '25.0' '69.0' '48.0'
 '41.0' '212.0' '296.0' '15.0' '778.0' '12.0' '52.0' '35.0' '23.0' '122.0'
 '173.0' '386.0' '24.0' '34.0' '39.0' '714.0' '45.0' '1.0' '82.0' '102.0'
 '92.0' '240.0' '108.0' '62.0' '17.0' '224.0' '303.0' '33.0' '103.0'
 '73.0' '53.0' '2503.0' '152.0' '110.0' '37.0' '127.0' '64.0' '225.0'
 '174.0' '3034.0' '49.0' '352.0' '54.0' '68.0' '19.0' '80.0' '27.0' '50.0'
 '96.0' '688.0' '36.0' '231.0' '85.0' '250.0' '100.0' '57.0' '89.0'
 '190.0' '211.0' '44.0' '52392.0' '160.0']
['0.0' '5.0' '15.0' '428.0' '1848.0' '141.0' '1173.0' '9.0' '939.0' '53.0'
 '539.0' '110.0' '11.0' '61.0' '67.0' '27.0' '140.0' '57.0' '432.0'
 '1528.0' '3.0' '49.0' '185.0' '230.0' '23.0' '89.0' '186.0' '31.0' '54.0'
 '534.0' '6.0' '41.0' '32.0' '16.0' '50.0' '1037.0' '8.0' '377.0' '2602.0'
 '99.0' '635.0' '392.0' '78.0' '172.0' '116.0' '386.0' '107.0' '195.0'
 '134.0' '490.0' '1181.0' '77.0' '1001.0' '595.0' '83.0' '455.0' '32867.0'
 '4625.0' '281.0' '156.0' '451.0' '131.0' '280.0' '123.0' '2212.0' '222.0'
 '4405.0' '15254.0' '521.0' '161687.0' '181.0' '242.0' '194.0' '47.0'
 '210.0' '270.0' '975.0' '152.0' '147.0' '59.0' '43.0' '825.0' '4.0'
 '64.0' '92.0' '320.0' '850.0' '37.0' '120.0' '213.0' '490000.0' '9900.0'
 '220.0' '112.0' '746.0' '100.0' '2311.0' '1042.0' '1676.0' '263.0'
 '405.0' '154.0' '264.0' '1889.0' '2819.0' '102.0' '249.0' '240.0' '84.0'
 '307.0' '3612.0' '393.0' '104.0' '275.0' '51.0' '340.0' '190.0' '3114.0'
 '304.0' '2195.0' '18.0' '65.0' '115.0' '623.0' '179.0' '329.0' '285.0'
 '192.0' '79.0' '215.0' '17.0' '34.0' '3947.0' '95.0' '73.0' '1158.0'
 '637.0' '371.0' '373.0' '38.0' '5966.0' '277.0' '76.0' '2881.0' '10.0'
 '370.0' '901.0' '896.0' '193.0' '155.0' '20.0' '447.0' '6832.0' '322.0'
 '56.0' '35.0' '391.0' '182.0' '418.0' '420.0' '6300.0' '300.0' '81.0'
 '480.0' '607.0' '130.0' '520.0' '716.0' '282.0' '19.0' '6179.0' '1.0'
 '203.0' '463.0' '1400.0' '670.0' '318.0' '296.0' '9552.0' '87.0' '223.0'
 '510.0' '233.0' '2700.0' '3212.0' '1414.0' '2948.0' '125.0' '22.0'
 '261.0' '227.0' '1600.0' '33.0' '170.0' '429.0' '106.0' '70.0' '505.0']
['11.0' '0.0' '6.0' '3.0' '5.0' '7.0' '4.0' '61.0' '80.0' '229.0' '22.0'
 '17.0' '1.0' '2.0' '25.0' '71.0' '13.0' '12.0' '54.0' '35.0' '28.0'
 '10.0' '21.0' '31.0' '9.0' '40.0' '37.0' '34.0' '67.0' '32.0' '8.0'
 '30.0' '20.0' '15.0' '19.0' '125.0' '24.0' '23.0' '27.0' '165.0' '102.0'
 '56.0' '86.0' '14.0' '352.0' '59.0' '26.0' '782.0' '88.0' '49.0' '120.0'
 '51.0' '65.0' '117.0' '350.0' '531.0' '210.0' '127.0' '294.0' '151.0'
 '52.0' '429.0' '18.0' '75.0' '184.0' '720.0' '723.0' '46.0' '48.0'
 '4200.0' '450.0' '64.0' '2410.0' '393.0' '78.0' '53.0' '1159.0' '84.0'
 '16.0' '60.0' '139.0' '36.0' '150.0' '73.0' '158.0' '62.0' '57.0' '554.0'
 '47.0' '310.0' '33.0' '41.0' '39.0' '1400.0' '440.0' '560.0' '122.0'
 '79.0' '114.0' '29.0' '130.0' '2300.0' '251.0' '107.0' '92.0' '100.0'
 '152.0' '44.0' '223.0' '77.0' '170.0' '200.0' '3300.0' '383.0']
['0.0' '8.0' '3.0' '7.0' '4.0' '14.0' '13.0' '2.0' '6.0' '5.0' '34.0'
 '16.0' '35.0' '11.0' '65.0' '25.0' '1.0' '9.0' '20.0' '138.0' '26.0'
 '10.0' '112.0' '82.0' '37.0' '19.0' '15.0' '36.0' '17.0' '209.0' '43.0'
 '67.0' '244.0' '308.0' '322.0' '39.0' '654.0' '1186.0' '111.0' '61.0'
 '21.0' '91.0' '33.0' '63.0' '18.0' '90.0' '41.0' '75.0' '31.0' '12.0'
 '24.0' '274.0' '115.0' '213.0' '118.0' '126.0' '498.0' '109.0' '100.0'
 '795.0' '223.0' '40.0' '68.0' '50.0' '30.0' '294.0' '53.0' '142.0' '23.0'
 '93.0' '22.0' '27.0' '170.0' '42.0' '59.0' '201.0' '74.0' '45.0' '29.0'
 '119.0' '7623.0' '32.0']
['0.0' '5.0' '35.0' '12.0' '54.0' '69.0' '32.0' '41.0' '190.0' '18.0'
 '11.0' '13.0' '22.0' '2.0' '1.0' '7.0' '31.0' '36.0' '10.0' '180.0'
 '53.0' '14.0' '8.0' '90.0' '9.0' '70.0' '28.0' '37.0' '16.0' '58.0'
 '76.0' '187.0' '366.0' '185.0' '4491.0' '430.0' '124.0' '961.0' '17.0'
 '21.0' '4.0' '6.0' '33.0' '175.0' '243.0' '39.0' '145.0' '133.0' '23.0'
 '146.0' '19.0' '3.0' '42.0' '15.0' '30.0' '26.0' '20.0' '49.0' '110.0'
 '50.0' '564.0' '107.0' '91.0' '34.0' '62.0' '89.0' '2477.0' '64.0' '25.0'
 '111.0' '48.0' '244.0' '210.0' '167.0' '46.0' '139.0' '305.0' '24.0'
 '51.0' '66.0' '351.0' '930.0' '38.0' '52.0' '45.0' '1149.0' '143.0'
 '84.0' '259.0' '214.0' '1148.0' '19827.0' '47.0' '357.0' '220.0']
['0.0' '12.0' '68.0' '13.0' '5.0' '2.0' '18.0' '10.0' '11.0' '3.0' '4.0'
 '53.0' '17.0' '1.0' '57.0' '32.0' '8.0' '6.0' '93.0' '15.0' '31.0' '85.0'
 '16.0' '358.0' '105.0' '9.0' '88.0' '69.0' '307.0' '46.0' '21.0' '7.0'
 '163.0' '361.0' '34.0' '23.0' '39.0' '62.0' '479.0' '117.0' '173.0'
 '198.0' '25.0' '27.0' '424.0' '76.0' '19.0' '28.0' '26.0' '143.0' '41.0'
 '83.0' '30.0' '587.0' '102.0']
['0.0' '279.0' '6.0' '115.0' '30.0' '95.0' '22.0' '8162.0' '33.0' '56.0'
 '91.0' '55.0' '841.0' '760.0' '390.0' '155.0' '32.0' '45.0' '19.0'
 '178.0' '21.0' '10.0' '4900.0' '67.0' '106.0' '522.0' '110.0' '75.0'
 '530.0' '137.0' '120.0' '220.0' '51.0' '339.0' '394.0' '7.0' '1737.0'
 '84.0' '13.0' '59.0' '7600.0' '195.0' '62.0' '241.0' '100.0' '33074.0'
 '28.0' '222.0' '326.0' '147.0' '594.0' '70.0' '190.0' '142.0' '4.0'
 '480.0' '68.0' '41.0' '31.0' '17.0' '218.0' '23.0' '29.0' '92.0' '27.0'
 '111.0' '102.0' '548.0' '72.0' '24.0' '101.0' '57.0' '104.0' '66.0'
 '61.0' '193.0' '131.0' '16.0' '549.0' '2290.0' '1134.0' '176.0' '763.0'
 '2160.0' '78.0' '50.0' '2490.0' '2.0' '88.0' '330.0' '159.0' '132.0'
 '1400.0' '105.0' '138.0' '156.0' '167.0' '90.0' '170.0' '37.0' '39.0'
 '36.0' '653.0' '158.0' '46.0' '267.0' '43.0' '629.0' '20.0' '630.0'
 '2630.0' '183.0' '641.0' '423.0' '99.0' '613.0' '164.0' '58.0' '305.0'
 '482.0' '251.0' '207.0' '616.0' '3915.0' '304.0' '250.0' '35.0' '4100.0'
 '7744.0' '321.0' '2000.0' '237.0' '230.0' '117.0' '286.0' '25.0' '12.0'
 '18.0' '141.0' '83.0' '150.0' '3.0' '907.0' '130.0' '902.0' '64.0'
 '160.0' '96.0' '133.0' '41385.0' '1749.0' '192.0' '1522.0' '148.0'
 '112.0' '355.0' '52.0' '385.0' '113.0' '846.0' '372.0' '642.0' '181.0'
 '992.0' '1130.0' '407.0' '347.0' '1100.0' '172.0' '3308.0' '1669.0'
 '125.0' '127.0' '360.0' '42.0' '173.0' '2401.0' '188.0' '94.0' '163.0'
 '206.0' '65.0' '460.0' '171.0' '26.0' '2855.0' '179.0' '53.0' '121.0'
 '38.0' '49.0' '570.0' '8.0' '14.0' '520.0' '290.0' '590.0' '950.0'
 '1000.0' '146.0' '44.0' '9.0' '27089.0' '126.0' '478.0' '2780.0' '3600.0'
 '240.0' '1800.0' '980.0' '249.0' '69.0' '634.0' '196.0' '1200.0' '968.0'
 '97.0' '426.0' '6299.0' '144.0' '5.0' '114.0' '11.0' '258.0' '59639.0'
 '280.0' '71.0' '89.0' '226.0' '128.0' '201.0' '925.0' '1500.0' '63.0']
['1573.0' '1554.0' '1966.0' '2231.0' '44.0' '21.0' '69.0' '1062.0'
 '2586.0' '6624.0' '51391.0' '1727.0' '1595.0' '4058.0' '7003.0' '7383.0'
 '1814.0' '6820.0' '11515.0' '21378.0' '2563.0' '5384.0' '858.0' '477.0'
 '47009.0' '1094.0' '614.0' '1168.0' '300.0' '1978.0' '127.0' '292.0'
 '440.0' '424.0' '63.0' '1200.0' '1001.0' '400.0' '140.0' '360.0' '970.0'
 '6300.0' '4624.0' '2184.0' '24177.0' '1000.0' '7435.0' '5368.0' '6174.0'
 '1700.0' '1931.0' '7680.0' '2789.0' '4246.0' '1579.0' '8584.0' '31.0'
 '3300.0' '2019.0' '2422.0' '13383.0' '135.0' '24221.0' '384895.0' '850.0'
 '13613.0' '2600.0' '1100.0' '7541.0' '1697.0' '5353.0' '1305.0' '1279.0'
 '7200.0' '1407.0' '4470.0' '340.0' '623.0' '6453.0' '11000.0' '2885.0'
 '1300.0' '24054.0' '4252.0' '15.0' '1282.0' '2077.0' '8.0' '1278.0'
 '5237.0' '5156.0' '1731.0' '3401.0' '4491.0' '1400.0' '55.0' '138.0'
 '592.0' '7375.0' '7836.0' '160.0' '190.0' '3161.0' '150.0' '10.0' '100.0'
 '640.0' '1.0' '5467.0' '810.0' '799.0' '3168.0' '7877.0' '472.0' '1943.0'
 '6939.0' '0.0' '9539.0' '14364.0' '11243.0' '6543.0' '10690.0' '1798.0'
 '18882.0' '3365.0' '4813.0' '2123.0' '1907.0' '23298.0' '390.0' '2005.0'
 '1813.0' '8220.0' '1031.0' '349.0' '854.0' '1110.0' '287.0' '3079.0'
 '272.0' '821.0' '696.0' '64.0' '4255.0' '82.0' '2158.0' '1673.0' '161.0'
 '2804.0' '3174.0' '42.0' '113.0' '200.0' '678.0' '170.0' '26.0' '62.0'
 '4527.0' '11875.0' '2218.0' '3375.0' '704.0' '847.0' '58.0' '553.0'
 '2300.0' '1076.0' '668.0' '3295.0' '6672.0' '819.0' '6291.0' '7398.0'
 '2181.0' '2277.0' '1500.0' '19.0' '47.0' '517.0' '2088.0' '1265.0'
 '1580.0' '27.0' '8580.0' '915.0' '784.0' '8872.0' '32.0' '374.0' '60.0'
 '620.0' '4588.0' '72.0' '29.0' '1318.0' '836.0' '81.0' '578.0' '257.0'
 '17.0' '366.0' '25.0' '5239.0' '36.0' '1601.0' '1778.0' '237.0' '4479.0'
 '6366.0' '6185.0' '6343.0' '5841.0' '878.0' '610.0' '3594.0' '1649.0'
 '700.0' '84.0' '3902.0' '19658.0' '180.0' '890.0' '6.0' '1406.0' '2875.0'
 '2713.0' '3077.0' '4296.0' '330.0' '250.0' '659.0' '2601.0' '259.0'
 '1736.0' '4531.0' '2990.0' '985.0' '13256.0' '995.0' '11258.0' '867.0'
 '1787.0' '1284.0' '1681.0' '5330.0' '1588.0' '102.0' '1557.0' '2166.0'
 '119.0' '2960.0' '1489.0' '410.0' '73.0' '582.0' '2201.0' '5438.0'
 '742.0' '2008.0' '6994.0' '632.0' '3518.0' '7477.0' '4346.0' '613540.0'
 '1481.0' '2287.0' '955.0' '1873.0' '992.0' '386.0' '439.0' '83.0'
 '3464.0' '12332.0' '11031.0' '2835.0' '1785.0' '92.0' '2010.0' '1421.0'
 '28.0' '1053.0' '95.0' '728.0' '483.0' '2800.0' '1900.0' '540.0' '130.0'
 '1939.0' '1982.0' '9583.0' '5943.0' '576.0' '4651.0' '15925.0' '5543.0'
 '6494.0' '168.0' '3065.0' '2204.0' '10409.0' '48433.0' '3954.0' '4511.0'
 '3362.0' '671.0' '3239.0' '1142.0' '1083.0' '1835.0' '2058.0' '10055.0'
 '399.0' '2899.0' '216.0' '1523.0' '2133.0' '901.0' '3974.0' '787.0'
 '206.0' '1486.0' '2566.0' '4520.0' '3.0' '37376.0' '2621.0' '8818.0'
 '4701.0' '747.0' '580.0' '5439.0' '209.0' '50.0' '1761.0' '430.0'
 '26864.0' '1472.0' '796.0' '4610.0' '210.0' '229.0' '12179.0' '5305.0'
 '1917.0' '71.0' '12259.0' '835.0' '488.0' '1948.0' '16.0' '531.0' '906.0'
 '10993.0' '38.0' '5.0' '46.0' '785.0' '2608.0' '70413.0' '10753.0'
 '2315.0' '3555.0' '1176.0' '932.0' '1807.0' '188.0' '4279.0' '1768.0'
 '792.0' '1947.0' '51.0' '760.0' '165.0' '719.0' '15458.0' '5941.0'
 '8380.0' '1689.0' '40569.0' '11190.0' '368.0' '12669.0' '998.0' '1130.0'
 '350.0' '1755.0' '560.0' '3271.0' '2630.0' '2900.0' '220.0' '2418.0'
 '171.0' '460.0' '3400.0' '701.0' '1087.0' '3921.0' '162.0' '20813.0'
 '569.0' '89.0' '10556.0' '9.0' '3081.0' '24374.0' '4125.0' '851.0' '12.0'
 '680.0' '326.0' '1416.0' '3059.0' '280.0' '325.0' '3106.0' '48.0'
 '1842.0' '7934.0' '2573.0' '392.0' '3813.0' '233.0' '5927.0' '920.0'
 '2100.0' '4224.0' '1536.0' '7783.0' '13130.0' '9898.0' '41.0' '10395.0'
 '4503.0' '2984.0' '1682.0' '4097.0' '1086.0' '2478.0' '473.0' '1181.0'
 '441.0' '103.0' '1172.0' '4528.0' '2668.0' '1548.0' '20884.0' '778.0'
 '1374.0' '514.0' '1346.0' '699.0' '1551.0' '1655.0' '4.0' '1914.0'
 '470.0' '3252.0' '3887.0' '3029.0' '22.0' '520.0' '85759.0' '1033.0'
 '3102.0' '450.0' '2272.0' '960.0' '2602.0' '863.0' '6400.0' '1218.0'
 '1945.0' '20.0' '2200.0' '4950.0' '3247.0' '8042.0' '434.0' '52.0'
 '136.0' '830.0' '320.0' '870.0' '57.0' '1658.0' '589.0' '370.0' '2.0'
 '33.0' '120.0' '201.0' '762.0' '7.0' '230.0' '1600.0' '3072.0' '4629.0'
 '2065.0']
['31.0' '3.0' '0.0' '1.0' '8.0' '9.0' '14.0' '5.0' '27.0' '10.0' '7.0'
 '16.0' '81.0' '34.0' '94.0' '1090.0' '66.0' '11.0' '17.0' '2.0' '80.0'
 '4.0' '59.0' '6.0' '21.0' '97.0' '20.0' '35.0' '15.0' '116.0' '45.0'
 '130.0' '71.0' '76.0' '26.0' '33.0' '56.0' '122.0' '24.0' '203.0' '70.0'
 '67.0' '158.0' '36.0' '12.0' '532.0' '25.0' '38.0' '640.0' '23.0' '19.0'
 '100.0' '41.0' '74.0' '86.0' '362.0' '1168.0' '179.0' '472.0' '112.0'
 '54.0' '113.0' '250.0' '30.0' '328.0' '380.0' '766.0' '252.0' '55.0'
 '13.0' '198.0' '65.0' '2473.0' '22.0' '182.0' '29.0' '68.0' '48.0' '64.0'
 '655.0' '151.0' '52.0' '79.0' '171.0' '58.0' '117.0' '162.0' '53.0'
 '210.0' '150.0' '46.0' '57.0' '63.0' '110.0' '18.0' '47.0' '128.0'
 '156.0' '475.0' '346.0' '8934.0' '174.0' '1142.0' '39.0']
['26949.0' '0.0' '4.0' '1.0' '13.0' '6270.0' '26.0' '3.0' '29.0' '5.0'
 '19.0' '6.0' '592.0' '290.0' '712.0' '21.0' '9.0' '790.0' '17.0' '11.0'
 '23.0' '7.0' '117.0' '88.0' '18.0' '2.0' '10.0' '32.0' '12.0' '46.0'
 '57.0' '1000.0' '14.0' '8.0' '49.0' '24.0' '42.0' '18459.0' '39.0'
 '275.0' '22.0' '37.0' '66.0' '15000.0' '16.0' '35.0' '93.0' '20.0' '33.0'
 '15.0' '64.0' '83.0' '106.0' '65.0' '155.0' '282.0' '30.0' '63.0' '60.0'
 '166.0' '1336.0' '123.0' '43.0' '28.0' '99.0' '195.0' '77.0' '44.0'
 '217.0' '82.0' '76.0' '125.0' '216.0' '62.0' '79.0' '303.0' '140.0'
 '645.0' '310.0' '745.0' '219.0' '1388.0' '1196.0' '75.0' '1510.0' '179.0'
 '67.0' '564.0' '1100.0' '346.0' '173.0' '164.0' '54.0' '61.0' '97.0'
 '25.0' '520.0' '256.0' '40.0' '198.0' '100.0' '45.0' '390.0' '707.0'
 '760.0' '820.0' '187.0' '440.0' '2700.0' '150.0' '160.0' '119.0' '53.0'
 '569.0' '344.0' '780.0' '48.0' '84.0' '129.0' '59.0' '51.0' '78.0'
 '406.0' '144.0' '73.0' '94.0' '70.0' '31.0' '80.0' '41.0' '452.0' '27.0'
 '12000.0' '830.0' '653.0' '133.0' '52.0' '87.0' '170.0' '68.0' '210.0'
 '74.0' '816.0' '34.0' '397.0' '36.0' '1061.0' '163.0' '408.0' '305.0'
 '336.0' '1348.0' '1330.0' '50.0' '174.0' '684.0' '151.0' '1499.0' '476.0'
 '424.0' '3365.0' '1043.0' '300.0' '114.0' '1087.0' '409.0' '199.0' '55.0'
 '81.0' '180.0' '245.0' '137.0' '640.0' '650.0' '38.0' '95.0' '794.0'
 '598.0' '370.0' '1679.0' '960.0' '118.0' '396.0' '1466.0' '116.0' '312.0'
 '270.0' '1700.0' '3100.0' '104.0' '1206.0' '940.0' '1505.0' '716.0'
 '227.0' '239.0' '235.0' '71.0' '266.0' '72.0' '226.0' '197.0' '178.0'
 '422.0' '1500.0' '251.0' '2847.0' '360.0' '411.0' '130.0' '283.0' '56.0'
 '240.0' '273.0' '350.0' '156.0' '209.0' '201.0' '34000.0' '320.0']
['192.0' '64.0' '390.0' '42.0' '160.0' '4.0' '500.0' '520.0' '244.0'
 '330.0' '345.0' '329.0' '37.0' '751.0' '126.0' '1652.0' '0.0' '116.0'
 '605.0' '156.0' '39.0' '159.0' '342.0' '470.0' '729.0' '2955.0' '1541.0'
 '6323.0' '510.0' '14.0' '67.0' '921.0' '210.0' '223.0' '55.0' '110.0'
 '335.0' '24.0' '49.0' '43.0' '400.0' '20.0' '286.0' '328.0' '896.0'
 '200.0' '3.0' '447.0' '578.0' '430.0' '83.0' '169.0' '431.0' '82.0'
 '347.0' '906.0' '123.0' '280.0' '1472.0' '18.0' '1188.0' '4009.0' '36.0'
 '1034.0' '420.0' '254.0' '410.0' '125.0' '92.0' '6500.0' '47.0' '1159.0'
 '97.0' '103.0' '171.0' '150.0' '649.0' '27.0' '41091.0' '4398.0' '2522.0'
 '8.0' '295.0' '2091.0' '1698.0' '86.0' '356.0' '394.0' '3900.0' '1186.0'
 '59.0' '62.0' '130.0' '348.0' '270.0' '5834.0' '1.0' '15.0' '2.0' '312.0'
 '87.0' '94.0' '81.0' '372.0' '75.0' '154.0' '236.0' '1082.0' '290.0'
 '2895.0' '946.0' '407.0' '298.0' '908.0' '1689.0' '306.0' '534.0' '190.0'
 '207.0' '1305.0' '152.0' '151.0' '16.0' '669.0' '465.0' '228.0' '216.0'
 '406.0' '11961.0' '955.0' '541.0' '308.0' '211.0' '9862.0' '69.0' '9.0'
 '10.0' '21.0' '920.0' '4652.0' '230.0' '13.0' '402.0' '482.0' '620.0'
 '1875.0' '1563.0' '823.0' '383.0' '73.0' '339.0' '641.0' '1225.0'
 '3161.0' '630.0' '2962.0' '132.0' '1109.0' '256.0' '610.0' '260.0'
 '105.0' '79.0' '568.0' '242.0' '224.0' '138.0' '991.0' '220.0' '142.0'
 '2575.0' '99.0' '252.0' '2516.0' '5.0' '480.0' '120.0' '111.0' '740.0'
 '166.0' '23.0' '1941.0' '387.0' '143.0' '35.0' '454.0' '415.0' '337.0'
 '235.0' '860.0' '640.0' '44794.0' '66.0' '300.0' '1100.0' '341.0'
 '2514.0' '625.0' '1084.0' '360.0' '377.0' '866.0' '141.0' '1543.0'
 '19786.0' '1303.0' '2888.0' '1372.0' '255.0' '1380.0' '1564.0' '168.0'
 '1768.0' '653.0' '5675.0' '127.0' '3193.0' '1062.0' '6.0' '208.0' '118.0'
 '4100.0' '351.0' '762.0' '2200.0' '40.0' '582.0' '2300.0' '357.0' '119.0'
 '514.0' '452.0' '1971.0' '416.0' '58.0' '177.0' '188.0' '149.0' '198.0'
 '46.0' '1830.0' '262.0' '561.0' '858.0' '3786.0' '61.0' '77.0' '2095.0'
 '3816.0' '164.0' '524.0' '57000.0' '250.0' '231.0' '2105.0' '1065.0'
 '1413.0' '608.0' '128.0' '1006.0' '2133.0' '1530.0' '296.0' '703.0'
 '321.0' '338.0' '139.0' '674.0' '291.0' '57.0' '229.0' '414.0' '2420.0'
 '31.0' '358.0' '403.0' '489.0' '2866.0' '634.0' '473.0' '728.0' '780.0'
 '32551.0' '386.0' '3413.0' '512.0' '530.0' '11.0' '3111.0' '56.0' '271.0'
 '467.0' '838.0' '288.0' '71.0' '273.0' '1283.0' '173.0' '763.0' '983.0'
 '1631.0' '1271.0' '424.0' '78.0' '227.0' '182.0' '9918.0' '2475.0'
 '495.0' '53.0' '314.0' '632.0' '191.0' '744.0' '253.0' '364.0' '692.0'
 '95.0' '857.0' '839.0' '563.0' '10843.0' '124.0' '1107.0' '310.0' '100.0'
 '461.0' '50.0' '11000.0' '135.0' '3165.0' '650.0' '790.0' '612.0'
 '4368.0' '588.0' '485.0' '1300.0' '203.0' '269.0' '44.0' '4217.0'
 '3778.0' '3482.0' '108.0' '880.0' '261.0' '3234.0' '241.0' '2394.0'
 '101.0' '33.0' '1234.0' '333.0' '3200.0' '4700.0' '8430.0' '172.0'

Certain values aren't complete: i.e '2,1'. what should we do about this. Should we add 0? should we remove them?
What should we do about these values: '330,74'?
What should i do about['ND,<2'],['1,1' '1<']

In [41]:
df.head()

,City,State,Zip,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,...,Immune_chronicmonoorepstein-barrvirus,Immune_frequentherpesoutbreaks,Immune_viralinfectionsbecomebacterial,Immune_increasedsusceptibilitytocancer,Reproductive_changesinmenstrualcycle,Reproductive_inconsistentmenstrualcycle,Reproductive_vaginalyeastorbacterialinfections,Reproductive_jockitch,Reproductive_infertilityinbothgenders,Reproductive_hormoneimbalances
0,Mountain Brook,Alabama,35223,0.0,0.0,14.0,0.0,0.0,11.0,0.0,...,0,0,0,0,1,1,1,1,1,1
1,Wasilla,Alaska,99623,0.0,0.0,12.0,0.0,5.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,1
2,Soldotna,Alaska,99669-8654,0.0,3.0,3.0,234.0,0.0,6.0,0.0,...,1,0,0,0,1,1,0,0,0,1
3,Soldotna,Alaska,99669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,Anchorage,Alaska,99508-4014,64.0,5.0,32.0,0.0,0.0,6.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
print(df.iloc[:, 39].head(600).unique())
print(df.iloc[:, 2].head(600).unique())

['6' '0' '12' '7' '5' '20' '10' '3' '46' '8' '61' '17' '2' '150' '22'
 '170' '11' '26' '18' '13' '4' '1' '49' '38' '209' '30' '270' '9' '14'
 '24' '75' '143' '15' '21' '47' '67' '63' '34' '133' '44' '2269' '37'
 '290' '40' '866' '28' '167' '65' '159' '230' '33' '189' '27' '140' '180'
 '56' '107' '31' '194' '69' '29']
['35223' '99623' '99669-8654' '99669' '99508-4014' 'T8A6P1' 'T0M0R0'
 'T2W 4C1' '85251' '85701' '85743' '86406' '85213' '85142' '85024' '85255'
 '85044' '86351-6965' '85204' '85745-8930' '85044-7048' '86001-2874'
 '85253' '85041' 'Az 85331' '72758' '72703-2072' '72110' '72701-6616'
 '72714' 'V0C 1Y0' 'V0N 1G1' 'V0N 1B8' '92646' '90066' '92119' '92011'
 '94526' '90265' '91354' '92037' '90815' '95014' '95618' '91311' '93257'
 '95123' '94010' '94960' '92870' '94025' '92103' '95482' '94301' '95136'
 '91107' '92532' '90806' '94904' '90041' '90049' '91360' '95713'
 '90068-2602' '94904-1155' '91387' '95826' '92108' '93401-7832' '92253'
 '95330-9473' '91343' '96003-5434' '91791' '94065-1173' '92647-5029'
 '92127' '91803' '92603-3536' '94558' '91602-2405' '90046-1214' '95765'
 '94022' '95926-7136' '92040-1252' '90254-2016' '95630-6368' '94501'
 '91786-4619' '94025-3663' '93711' '95062-3547' '91360-5924' '94804-1541'
 '90028-5678' '93420-5361' '94708-1222' '94954-3674' '92124-2017'
 '95762-3959' '94110' '94549' '91367-2213' '90046' '92688-1036' '96073'
 '91205-3448' '92118-1450' '92010' '91316-4116' '92675' '80538' '80004'
 '80104' '80501' '80112' '81521' '80108' '80501-8811' '80526-3040' '80020'
 '80124' '80528' '80906' '6117' '6831' '6810' '06437-1808' '19803' '32034'
 '34238' '32168' '33624' '33707' '33134' '32601' '33149' '33331' '34240'
 '32707' '32250' '34135' '33139' '33127' '34984' '34232-6611' '33064-7241'
 '32703-4773' '33304' '33321' '0' 'M1 5QU' '30066' '30263' '31789' '31558'
 '30341' '30518' '30269-1322' '30305' '96793' '83836' '83541' '83702'
 '83642-6156' '83642' '83616' '83616-7185' '83616-4177' '83706-6302'
 '60070' '60626' '60103' '61704' '60014' '60087-5329' '60048' '60174-2843'
 '60514' '60614' '60525-3150' '60148-2528' '60527-5343' '61265'
 '60045-3118' '60446' '60625-5937' '62549' '46202' '46074' '47119-9264'
 '46037' '46723-9603' '46060' '46060-1519' '46953' '47404' '46077-7823'
 '46725' '46062-5002' '52807-1228' '52601-3485' '52247' '50514-7574'
 '67226' '67063' '66502' '66062' '67218-1305' '42134' '40383' '40511-8790'
 '40383-1306' '70510' '70809-1789' '70809' '04270-6827' '4986' '4345'
 '04072-3502' '20901' '20852' '21204' '21771-9535' '21784-6113'
 '20854-1172' '20833' '20817-5925' '20733-9609' '21155' '2141' '2703'
 '1938' '2649' '1923' '2145' '2030' '01945-1223' '2052' '2149'
 '01002-1267' '1301' '49682' '48005' '48390' '48374' '48072-2082' '49323'
 '48346' '49004' '48101-2300' '49837-2425' '49316-7432' '48867-8200'
 '48105-2508' '55445' '55442' '55337' '55973' '55082' '55011' '55353-4513'
 '64014' '64801' '63025' '64157-7948' '63026-3420' '65109' '63368' '64138'
 '63367' '63304' '63304-1084' '64024' '59808' '590444' '59715' '59901'
 '59030' '59068-9251' '59047' '28210' '8002' '97190' 'LE12 8DH' 'SK9 4DA'
 '96349' 'SAN PEDRO GARZA GARCIA' 'SG6 1AD' '2567' '3153' 'Rutland' '3763'
 '4941 JD' '3442' '57165' '02-69' '31978' '28232' '68506' '68022' '68956'
 '89012' '89511' '89509-6904' '89436' '89436-7090' '89149' '3031' '3076'
 '3307' '7430' '7757' '7302' '7307' '8610' '08003-3132' '8848' '7930'
 '07092-2006' '8003' '7069' '7417' '7403' '87508' '87108' '87506' '88061'
 '11552' '14850' '11211' '12065' '12203' '11385' '10028' '11572' '11201'
 '11231-5014' '11210-5237' '11213-3491' '10013' '11249' '11772-2950'
 '11377' '10530-1157' '10003' '11963' '13045' '12603-4912' '11226-3703'
 '27520' '27013' '28278' '28204' '27502' '27523' '28227-8153' '27340'
 '28590-9163' '27302' '28204-3306' '28805-1342' '28056-8416' '28277'
 '27052' '27615-4079' '27516-1511' '58701' '58318' 'B0K1L0' '45430'
 '44313' '45255' '44107' '45071' '44126-1248' '44116' '44202-7659' '45140'
 '43015' '44857-2427' '45002' '43431' '44011-1249' '44012' '43015-1274'
 '74011' '74135' '73150' 'K2K 2S4' 'P3A 5P8' 'K0C 1Z0' 'L3Z 4K1' 'L6M 0H3'
 'P0J10' 'N5R 3S9' '97530' '97487' '97203-4234' '97306-6909' '97404'
 '97051-2723' '97062-9552' '97068' '97374-9766' '97031' '97333-2928'
 '97220' '97089-8860' '97330' '16066' '15401' '17517' '15214' '19106'
 '19046' '19333' '15068' '15222' '17044' '19335-4135' '17007-9415' '17257'
 '19094-1013' '19033-2211' '19335-2031' '17013-1604' '19460' '19006-4719'
 'J0P 1Z0' 'J0X 3G0' 'S6H 3R7' '29620' '29684' '29407' '29412-4545'
 '37363' '37075' '37206' '37803' '37072-7147' 'TN' '38224' '37064' '37205'
 '37334' '77304' '78130' '78249' '76177' '78704' '78748' '78732' '76643'
 '75966-6305' 'Temple' '78741-3709' '75214-4006' '78746-3432' '78759-6906'
 '77057-1617' '78727-6628' '75077-1827' '79706-1720' '76856' '75701-8243'
 '76008' '78745-3793' '76227' '77389-1556' '78660' '78163' '78757'
 '78204-2408' '75025-3446' '78109' '78636' '78717' '78132' '75028'
 '78747-1925' '78006' '84095' '84065' '84081-5085' '5404' '5494' '23456'
 '23233' '22642' '22812' '23703' '22042' '23112' '22206' '22902-5437'
 '20105-6218' '20147-4431' '23116' '23231-1207' '20121' '23235-6202'
 '23320-2955' '24503-3857' '20148' '98177' '98391' '98373' '98125' '98682'
 '98037' '98087' '99037' '98226' '99353-7420' '98033' '98059' '99207'
 '98229-2700' '98199' '98264' '99212' '98052' '98584' '98027' '98107-2319'
 '98072-9800' '98027-5607' '98027-5609' '54913' '54491' '53142' '53563'
 '54022-5604' '53221' '53211' '53189-7102' '82072' '82718']

In [43]:
df.dtypes

City                                              object
State                                             object
Zip                                               object
Aspergillus flavus/oryzae                         object
Aspergillus fumigatus                             object
                                                   ...
Reproductive_inconsistentmenstrualcycle            int64
Reproductive_vaginalyeastorbacterialinfections     int64
Reproductive_jockitch                              int64
Reproductive_infertilityinbothgenders              int64
Reproductive_hormoneimbalances                     int64
Length: 163, dtype: object

In [50]:
for i in mole_columns:
    df[i]= df[i].astype(float).astype(int)
df.head()
df.shape

(581, 163)

In [51]:
from sklearn.cluster import KMeans

In [55]:
print(df[['Sum of the Logs (Group I)', 'Sum of the Logs (Group II)']].head())

   Sum of the Logs (Group I)  Sum of the Logs (Group II)
0                         25                       16.60
1                         13                       11.00
2                         22                       15.70
3                         10                       10.00
4                         17                       11.45

In [56]:
df = df.drop(['Sum of the Logs (Group I)', 'Sum of the Logs (Group II)'], axis=1)

In [74]:
features = df.iloc[:, 3:39]
features.head()

,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,Aspergillus sydowii,Aspergillus unguis,Aspergillus versicolor,...,Acremonium strictum,Alternaria alternata,Aspergillus ustus,Cladosporium cladosporioides 1,Cladosporium cladosporioides 2,Cladosporium herbarum,Epicoccum nigrum,Mucor amphibiorum*,Penicillium chrysogenum,Rhizopus stolonifer
0,0,0,14,0,0,11,0,0,0,0,...,9,19,15,0,0,0,372,10,29,6
1,0,0,12,0,5,0,0,0,0,0,...,0,0,0,470,12,114,67,24,111,0
2,0,3,3,234,0,6,0,5,0,279,...,0,0,119,0,0,0,60,173,70,0
3,0,0,0,0,0,0,0,0,0,6,...,0,0,0,0,0,0,435,4,49,0
4,64,5,32,0,0,6,0,0,0,6,...,2,3,0,0,0,0,2,7,83,12

In [77]:
data = features.copy()
data.head()

,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,Aspergillus sydowii,Aspergillus unguis,Aspergillus versicolor,...,Acremonium strictum,Alternaria alternata,Aspergillus ustus,Cladosporium cladosporioides 1,Cladosporium cladosporioides 2,Cladosporium herbarum,Epicoccum nigrum,Mucor amphibiorum*,Penicillium chrysogenum,Rhizopus stolonifer
0,0,0,14,0,0,11,0,0,0,0,...,9,19,15,0,0,0,372,10,29,6
1,0,0,12,0,5,0,0,0,0,0,...,0,0,0,470,12,114,67,24,111,0
2,0,3,3,234,0,6,0,5,0,279,...,0,0,119,0,0,0,60,173,70,0
3,0,0,0,0,0,0,0,0,0,6,...,0,0,0,0,0,0,435,4,49,0
4,64,5,32,0,0,6,0,0,0,6,...,2,3,0,0,0,0,2,7,83,12

In [78]:
data = ((data - data.min()) / (data.max()-data.min())) * 9 + 1

In [79]:
data.describe()

,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,Aspergillus sydowii,Aspergillus unguis,Aspergillus versicolor,...,Acremonium strictum,Alternaria alternata,Aspergillus ustus,Cladosporium cladosporioides 1,Cladosporium cladosporioides 2,Cladosporium herbarum,Epicoccum nigrum,Mucor amphibiorum*,Penicillium chrysogenum,Rhizopus stolonifer
count,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,...,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000,581.000000
mean,1.039733,1.029302,1.217422,1.020739,1.026778,1.119329,1.038916,1.032858,1.150841,1.078724,...,1.118390,1.127412,1.106144,1.307469,1.174723,1.113299,1.035738,1.239968,1.074775,1.060173
std,0.380808,0.397658,0.604017,0.374384,0.393978,0.602829,0.383609,0.387586,0.723291,0.536830,...,0.608708,0.494993,0.578141,0.810799,0.665445,0.578412,0.376723,0.783627,0.476215,0.418222
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000380,1.014010,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.002343,1.006561,1.000000,1.000000,1.000000,1.000000,1.001186,1.014469,1.001596,1.000000
50%,1.002953,1.001141,1.050558,1.000344,1.000000,1.010714,1.000000,1.000000,1.000000,1.005282,...,1.011717,1.026244,1.006274,1.000000,1.000000,1.000000,1.004727,1.053744,1.005674,1.000000
75%,1.017717,1.003995,1.160203,1.002061,1.002020,1.049286,1.011806,1.005447,1.030664,1.021731,...,1.039839,1.093494,1.034507,1.208696,1.046875,1.023739,1.016194,1.163298,1.021100,1.023799
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [86]:
data.head()

,Aspergillus flavus/oryzae,Aspergillus fumigatus,Aspergillus niger,Aspergillus ochraceus,Aspergillus penicillioides,Aspergillus restrictus*,Aspergillus sclerotiorum,Aspergillus sydowii,Aspergillus unguis,Aspergillus versicolor,...,Acremonium strictum,Alternaria alternata,Aspergillus ustus,Cladosporium cladosporioides 1,Cladosporium cladosporioides 2,Cladosporium herbarum,Epicoccum nigrum,Mucor amphibiorum*,Penicillium chrysogenum,Rhizopus stolonifer
0,1.000000,1.000000,1.008528,1.000000,1.000000,1.023571,1.0,1.00000,1.0,1.000000,...,1.010546,1.015582,1.047055,1.000000,1.000000,1.000000,1.005804,1.020671,1.005142,1.023799
1,1.000000,1.000000,1.007310,1.000000,1.000092,1.000000,1.0,1.00000,1.0,1.000000,...,1.000000,1.000000,1.000000,1.113527,1.051136,1.020817,1.001045,1.049610,1.019681,1.000000
2,1.000000,1.000571,1.001827,1.040197,1.000000,1.012857,1.0,1.00227,1.0,1.042103,...,1.000000,1.000000,1.373301,1.000000,1.000000,1.000000,1.000936,1.357602,1.012412,1.000000
3,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1.0,1.000905,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.006787,1.008268,1.008688,1.000000
4,1.188976,1.000951,1.019492,1.000000,1.000000,1.012857,1.0,1.00000,1.0,1.000905,...,1.002343,1.002460,1.000000,1.000000,1.000000,1.000000,1.000031,1.014469,1.014717,1.047598

In [87]:
def random_centroids(data, k):
    centroids=[]
    for i in range (k):
        centroid = centroid = data.apply(lambda x: float (x.sample()))
        centroids.append(centroid)
    return pd.concat(centroids, axis=1)

In [88]:
centroids = random_centroids(data, 5)

/tmp/ipykernel_3101/382446592.py:4: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  centroid = centroid = data.apply(lambda x: float (x.sample()))

In [89]:
centroids

,0,1,2,3,4
Aspergillus flavus/oryzae,1.002953,1.000000,1.000000,1.000000,1.005906
Aspergillus fumigatus,1.003234,1.001902,1.000761,1.004375,1.006278
Aspergillus niger,1.118782,1.006701,4.167513,1.692589,1.004264
Aspergillus ochraceus,1.000000,1.001374,1.007902,1.000000,1.000000
Aspergillus penicillioides,1.000000,1.000000,1.004831,1.000000,1.000000
Aspergillus restrictus*,1.002143,1.000000,1.042857,1.006429,1.053571
Aspergillus sclerotiorum,1.000000,1.002361,1.005903,1.000000,1.000000
Aspergillus sydowii,1.000000,1.009986,1.000000,1.004993,1.000000
Aspergillus unguis,1.076661,1.000000,1.015332,1.000000,1.000000
Aspergillus versicolor,1.000000,1.000000,1.136874,1.040292,1.027013
Aureobasidium pullulans,1.000235,1.018747,1.101788,1.080195,1.039137
Chaetomium globosum,1.000000,1.000000,1.004030,1.152116,1.003022
Cladosporium sphaerospermum,1.002912,1.000794,1.006882,1.000794,1.002912
Eurotium (Asp.) amstelodami*,1.057724,1.001397,1.191483,1.017069,1.014276
Paecilomyces variotii,1.008223,1.000000,1.000484,1.004595,1.000000
Penicillium brevicompactum,1.002069,1.021005,1.000000,1.016039,1.000000
Penicillium corylophilum,1.000000,1.002993,1.172113,5.708406,1.023946
Penicillium crustosum*,1.115579,1.003316,1.000000,1.000000,1.011368
Penicillium purpurogenum,1.043624,1.000000,1.000000,1.255034,1.000000
Penicillium spinulosum*,1.000000,1.003222,1.000000,1.000000,1.001611
Penicillium variabile,1.014501,1.000000,1.178840,1.000000,1.299678
Scopulariopsis brevicaulis/fusca,1.000000,1.014486,1.039319,1.000000,1.024833
Scopulariopsis chartarum,1.000000,1.000001,1.000001,1.000000,1.000003
Stachybotrys chartarum,1.077586,1.360222,1.000000,1.000000,1.202278
Trichoderma viride*,1.173428,1.025101,1.241886,1.002282,1.031947
Wallemia sebi,1.055268,1.003491,1.007563,1.011054,1.051196
Acremonium strictum,1.000000,1.021091,1.000000,1.060930,1.009374
Alternaria alternata,1.015582,1.000000,1.000000,1.106616,1.055768
Aspergillus ustus,1.084699,1.069014,1.000000,1.018822,1.000000
Cladosporium cladosporioides 1,1.000000,1.000000,1.000000,1.000000,1.000000
Cladosporium cladosporioides 2,1.000000,1.409091,1.000000,1.000000,1.294034
Cladosporium herbarum,1.000000,1.000000,1.085824,1.006574,1.000000
Epicoccum nigrum,1.015446,1.000250,1.000374,1.002278,1.007894
Mucor amphibiorum*,1.020671,1.012402,1.024805,1.020671,1.316261
Penicillium chrysogenum,1.000000,1.004078,1.033689,1.006915,1.000000
Rhizopus stolonifer,1.000000,1.000000,1.000000,1.000000,1.011900

In [90]:
centroid

Aspergillus flavus/oryzae           1.011811
Aspergillus fumigatus               1.000000
Aspergillus niger                   1.009137
Aspergillus ochraceus               1.000000
Aspergillus penicillioides          1.000000
Aspergillus restrictus*             1.036429
Aspergillus sclerotiorum            1.000000
Aspergillus sydowii                 1.023150
Aspergillus unguis                  1.000000
Aspergillus versicolor              1.001056
Aureobasidium pullulans             1.093881
Chaetomium globosum                 1.008059
Cladosporium sphaerospermum         1.019853
Eurotium (Asp.) amstelodami*        1.012103
Paecilomyces variotii               1.000242
Penicillium brevicompactum          1.089816
Penicillium corylophilum            1.014218
Penicillium crustosum*              1.000000
Penicillium purpurogenum            1.000000
Penicillium spinulosum*             1.000000
Penicillium variabile               1.077336
Scopulariopsis brevicaulis/fusca    1.000000
Scopulariopsis chartarum            1.000000
Stachybotrys chartarum              1.000000
Trichoderma viride*                 1.155172
Wallemia sebi                       1.022689
Acremonium strictum                 1.000000
Alternaria alternata                1.003280
Aspergillus ustus                   1.000000
Cladosporium cladosporioides 1      1.000000
Cladosporium cladosporioides 2      1.000000
Cladosporium herbarum               1.000000
Epicoccum nigrum                    1.006428
Mucor amphibiorum*                  1.055811
Penicillium chrysogenum             1.030674
Rhizopus stolonifer                 1.003967
dtype: float64

In [95]:
def get_labels (data, centroids):
    distances = centroids.apply(lambda x: np.sqrt(((data- x) ** 2).sum(axis = 1)))
    return distances.idxmin(axis=1)

In [96]:
labels = get_labels(data, centroids)
labels.value_counts()

0    424
4     99
1     38
2     17
3      3
Name: count, dtype: int64

In [100]:
def new_centroids (data, labels, k):
    return data.groupby(labels).apply(lambda x: np.exp(np.log(x).mean())).T